### PR TITLE
10 user automated test

### PR DESCRIPTION
**Pull request by VictorsCodingCorner**
I've added ser tests in user.spec.js. 
The coverage tool is disabled (0 is the accepted %) now as it still is broken, the report can still be viewed. 

To test if this works check the pull request how the tests execute.

### CODE REVIEW

**Comment by VictorsCodingCorner** [comment]
Ni kan gå in här och kolla på testerna och rapposrten:
image

**Review by Badde00 — APPROVED** [review]
Approved

**Review by sebgro98 — APPROVED** [review]
Approved

**Comment by amos1969** [comment]
Approved

**Pull request merged**
