### PR TITLE
Implement cohort model in domain and route folders, and controller

### PR DESCRIPTION
**Pull request by maaxolofsson**

### CODE REVIEW

**Review by Badde00 — CHANGES_REQUESTED** [review]
- You get a ```201 Created``` code when sending a get to ```/cohorts/1```. It should be a 200
- Please update the spec to display what the expected input data is when making a post request.
- Update the spec in general to include the new endpoints. It's really hard to test when I don't know the expected inputs.
- Not a requirement, but might I suggest the post endpoint ```/cohorts/:cohortId/addUser``` with user in body or even ```/cohorts/:cohortId/addUser/:userId```. It's a bit more easy to understand and closer to how the rest of your endpoints work.
- Maybe don't include the hashed user password in the return statement for when you add a user to a cohort

**Review by Badde00 — APPROVED** [review]
Approved

**Review by sebgro98 — APPROVED** [review]
Approved

**Comment by amos1969** [comment]
Approved

**Pull request merged**
