### PR TITLE
GET endpoints for posts

### PR DESCRIPTION
**Pull request by maaxolofsson**
Implemented GET endpoints (getAll, getById) for posts. Also updated API spec to reflect this.
Tested the endpoints using Insomnia.

You can test this out by visiting the get endpoints /posts and post/id.

### CODE REVIEW

**Review by Badde00 — APPROVED** [review]
Approved

**Comment by LudwigJL** [comment]
How it looks in insomnia:
Get all posts 
Screenshot 2024-10-30 162422

Get post by id
Screenshot 2024-10-30 162528

**Review by sebgro98 — APPROVED** [review]
Approved

**Review by Badde00 — APPROVED** [review]
Approved

**Comment by amos1969** [comment]
Approved

**Pull request merged**
