### PR TITLE
41-post-automated-test

### PR DESCRIPTION
**Pull request by VictorsCodingCorner**
added post.spec.js, covers around 70% of post. Given the time this will have to suffice.
I also enabled the check-coverage as we soon launch. 

Tests ``save``, ``findById`` and ``findAll`` as whit the user pull request the result of the automated test can be viewed. 

Should be up to date with Main so hopefully no conflicts, let me know if there are any issues.

### CODE REVIEW

**Review by FredrikEH — DISMISSED** [review]

**Review by sebgro98 — CHANGES_REQUESTED** [review]
You have to change every field that consists of  "githubUrl" To "githubUsername" with the new changes

**Review by sebgro98 — APPROVED** [review]
Approved

**Review by Badde00 — APPROVED** [review]
Approved

**Comment by amos1969** [comment]
Approved

**Pull request merged**
