### PR TITLE
coverage tool should now work. Had to switch from nyc to c8. 

### PR DESCRIPTION
**Pull request by VictorsCodingCorner**
coverage tool should now work. Had to switch from nyc to c8. still works in the same way. 

You should be able to see a report in this pull request. Will provide a print once I open this.

### CODE REVIEW

**Comment by VictorsCodingCorner** [comment]
You can click on "Run Jasmine tests" details. 

image

to see the following now:

image

**Review by Badde00 — APPROVED** [review]
Approved

**Review by sebgro98 — APPROVED** [review]
Approved

**Comment by amos1969** [comment]
Approved

**Pull request merged**
